# Generated by Django 2.2.10 on 2021-11-09 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('kind', models.IntegerField(choices=[(1, 'text'), (2, 'one choice'), (3, 'few choices')], default=2)),
                ('choices', models.TextField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling_app.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300)),
                ('quest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polling_app.Question')),
                ('user_sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polling_app.UserSign')),
            ],
        ),
    ]
