# Generated by Django 2.2.10 on 2021-11-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.AlterField(
            model_name='poll',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=70)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest', to='polling_app.Question')),
            ],
        ),
    ]
