# Generated by Django 2.2.10 on 2021-11-09 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0002_auto_20211109_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling_app.Question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polling_app.Question'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
