# Generated by Django 2.2.10 on 2021-11-09 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0003_auto_20211109_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='polling_app.UserSign'),
        ),
        migrations.AlterField(
            model_name='usersign',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usersign',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
